<?php


namespace App\Service\Section;


abstract class BaseAbstract
{
    const COMMAND_UNDEFINED = 0;
    const COMMAND_BACK_TO_PREVIOUS_QUESTION = 18;
    const COMMAND_MAIN_MENU = 1;
    const COMMAND_CABINET = 2;
    const COMMAND_CABINET_BUY_COURSE_CATEGORIES = 3;
    const COMMAND_CABINET_BUY_COURSE_CATEGORY = 4;
    const COMMAND_CABINET_BUY_COURSE_LIST = 5;
    const COMMAND_ALL_COURSES_CATEGORIES = 6;
    const COMMAND_ALL_COURSES_CATEGORY = 7;
    const COMMAND_ALL_COURSES_LIST = 8;
    const COMMAND_SUPPORT_ADMIN_QUESTIONS_LIST = 9;
    const COMMAND_SUPPORT_ADMIN_QUESTION = 10;
    const COMMAND_SUPPORT_USER = 11;
    const COMMAND_MAILING = 12;
    const COMMAND_PROMOCODES = 13;
    const COMMAND_SETTINGS = 14;
    const COMMAND_SETTINGS_ADD_COURSE = 15;
    const COMMAND_SETTINGS_ADD_COURSE_SKIP_CATEGORY = 17;
    const COMMAND_SETTINGS_ADD_COURSE_SET_VISIBILITY = 19;
    const COMMAND_SETTINGS_ADMINS_LIST = 16;
    const COMMAND_SETTINGS_ADD_ADMIN = 20;
}