<?php


namespace App\Service\Section;


abstract class BaseAbstract
{
    const FILE_TYPE_DOCUMENT = 1;
    const FILE_TYPE_VIDEO = 2;
    const FILE_TYPE_PHOTO = 3;

    const COMMAND_UNDEFINED = 0;
    const COMMAND_BACK_TO_PREVIOUS_QUESTION = 18;
    const COMMAND_DELETE_MESSAGE = 26;
    const COMMAND_MAIN_MENU = 1;
    const COMMAND_CABINET = 2;
    const COMMAND_COURSES = 27;
    const COMMAND_COURSES_DOWNLOAD = 28;
    const COMMAND_CABINET_BUY_COURSE_CATEGORIES = 3;
    const COMMAND_CABINET_BUY_COURSE_CATEGORY = 4;
    const COMMAND_CABINET_BUY_COURSE_LIST = 5;
    const COMMAND_SUPPORT = 25;
    const COMMAND_SUPPORT_ADMIN_QUESTION = 10;
    const COMMAND_PROMOCODES = 13;
    const COMMAND_PROMOCODES_CREATE = 29;
    const COMMAND_PROMOCODES_CREATE_ITEMS = 33;
    const COMMAND_PROMOCODES_CREATE_SKIP_ITEM = 31;
    const COMMAND_PROMOCODES_CREATE_SELECT_ITEM = 32;
    const COMMAND_PROMOCODES_CREATE_SELECT_TYPE = 34;
    const COMMAND_PROMOCODES_EDIT_NAME_QUESTION = 35;
    const COMMAND_PROMOCODES_EDIT_ITEM = 41;
    const COMMAND_PROMOCODES_EDIT_ITEM_QUESTION = 36;
    const COMMAND_PROMOCODES_EDIT_EXPIRE_QUESTION = 37;
    const COMMAND_PROMOCODES_EDIT_DISCOUNT_QUESTION = 38;
    const COMMAND_PROMOCODES_REMOVE = 39;
    const COMMAND_PROMOCODES_INFO = 40;
    const COMMAND_SETTINGS = 14;
    const COMMAND_SETTINGS_ADD_COURSE = 15;
    const COMMAND_SETTINGS_ADD_COURSE_CATEGORIES = 24;
    const COMMAND_SETTINGS_ADD_COURSE_SKIP_CATEGORY = 17;
    const COMMAND_SETTINGS_ADD_COURSE_SELECT_CATEGORY = 23;
    const COMMAND_SETTINGS_ADD_COURSE_SET_VISIBILITY = 19;
    const COMMAND_SETTINGS_ADMINS_LIST = 16;
    const COMMAND_SETTINGS_ADD_ADMIN = 20;
    const COMMAND_SETTINGS_REMOVE_ADMIN = 21;
    const COMMAND_SETTINGS_REMOVE_ADMIN_CONFIRM = 22;
    const COMMAND_MAILING = 12;
    const COMMAND_MAILING_MENU = 48;
    const COMMAND_MAILING_BUTTONS = 42;
    const COMMAND_MAILING_FILE = 43;
    const COMMAND_MAILING_COURSES = 44;
    const COMMAND_MAILING_COURSE = 45;
    const COMMAND_MAILING_REMOVE_COURSE = 47;
    const COMMAND_MAILING_REMOVE_TEXT = 46;
    const COMMAND_MAILING_REMOVE_FILE = 49;
    const COMMAND_MAILING_WHOM = 50;
    const COMMAND_MAILING_WHOM_ALL = 51;
    const COMMAND_MAILING_WHOM_PROMOCODE = 52;
    const COMMAND_MAILING_WHOM_COURSE = 53;
    const COMMAND_MAILING_SEND = 54;
    const COMMAND_MAILING_WHOM_ALL_UNSELECT = 55;
    const COMMAND_MAILING_WHOM_PROMOCODE_UNSELECT = 56;
    const COMMAND_MAILING_WHOM_COURSE_UNSELECT = 57;
    const COMMAND_MAILING_WHOM_PROMOCODES = 58;
    const COMMAND_MAILING_WHOM_COURSES = 59;
}